"""Launch a shell source from runfiles without requiring mode 100755.

rules_shell symlinks `sh_test` / `sh_binary` srcs with `is_executable=True`.
Bazel rejects that symlink when the source file is not executable. GitHub's
contents API stores blobs as 100644, so a checkout of this repo must still
build. This rule writes a tiny executable launcher and puts the real script
in runfiles. The launcher `exec`s it with bash, so the source mode bit is
irrelevant.
"""

def _exec_shell_impl(ctx):
    src = ctx.file.src
    short = src.short_path
    if short.startswith("../"):
        short = short[3:]
        workspace = short.split("/", 1)[0]
        short = short.split("/", 1)[1] if "/" in short else short
    else:
        workspace = ctx.workspace_name

    launcher = ctx.actions.declare_file(ctx.label.name + ".launcher.sh")
    ctx.actions.write(
        output = launcher,
        is_executable = True,
        content = """#!/usr/bin/env bash
# Generated by //tools:exec_shell.bzl. Do not edit.
set -euo pipefail
short=%s
ws=%s

pick() {
  local root="$1"
  local candidate
  [[ -z ${root} ]] && return 1
  for candidate in \\
    "${root}/${ws}/${short}" \\
    "${root}/_main/${short}" \\
    "${root}/${short}"
  do
    if [[ -f ${candidate} ]]; then
      printf '%%s\\n' "${candidate}"
      return 0
    fi
  done
  return 1
}

src=""
zero="$0"
case "${zero}" in
  /*) ;;
  *) zero="${PWD}/${zero}" ;;
esac
if src="$(pick "${RUNFILES_DIR:-}")"; then
  :
elif src="$(pick "${TEST_SRCDIR:-}")"; then
  :
elif src="$(pick "${zero}.runfiles")"; then
  :
else
  echo "exec_shell: cannot locate ${short} (RUNFILES_DIR=${RUNFILES_DIR:-})" >&2
  exit 1
fi
exec bash "${src}" "$@"
""" % (repr(short), repr(workspace)),
    )
    runfiles = ctx.runfiles(files = [src] + ctx.files.data)
    return [DefaultInfo(files = depset([launcher]), runfiles = runfiles)]

exec_shell = rule(
    implementation = _exec_shell_impl,
    attrs = {
        "src": attr.label(
            allow_single_file = True,
            mandatory = True,
            doc = "Shell source to execute. Mode 100644 is fine.",
        ),
        "data": attr.label_list(
            allow_files = True,
            doc = "Extra runfiles the source script reads beside itself.",
        ),
    },
    doc = "Generated executable launcher for a non-executable shell source.",
)
